<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover">

    <xacro:arg name="use_sim" default="true"/>

    <xacro:property name="chassis_length" value="0.24"/>
    <xacro:property name="chassis_width" value="0.18"/>
    <xacro:property name="chassis_height" value="0.08"/>
    
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_width" value="0.04"/>
    
    <xacro:property name="wheel_offset_x" value="0.09"/> 
    <xacro:property name="wheel_offset_y" value="0.10"/>

    <link name="base_footprint"/>
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="Blue">
                <color rgba="0 0 1 1"/>
            </material>
            <origin xyz="0 0 ${chassis_height/2}"/>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <origin xyz="0 0 ${chassis_height/2}"/>
        </collision>
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry> <cylinder radius="0.03" length="0.04"/> </geometry>
            <material name="Red"><color rgba="1 0 0 1"/></material>
        </visual>
    </link>
    
    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0.05 0 ${chassis_height + 0.02}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel" params="prefix x_reflect y_reflect is_mimic parent_joint">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Black"><color rgba="0.1 0.1 0.1 1"/></material>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <inertial>
                <mass value="0.2"/>
                <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
            </inertial>
        </link>

        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Black</material>
            <mu1>1.0</mu1> 
            <mu2>1.0</mu2>
        </gazebo>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${x_reflect * wheel_offset_x} ${y_reflect * wheel_offset_y} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            
            <xacro:if value="${is_mimic}">
                <mimic joint="${parent_joint}" multiplier="1.0" offset="0.0"/>
            </xacro:if>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1" is_mimic="false" parent_joint=""/>
    <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1" is_mimic="false" parent_joint=""/>
    <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1" is_mimic="true" parent_joint="rear_left_wheel_joint"/>
    <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1" is_mimic="true" parent_joint="rear_right_wheel_joint"/>

    <ros2_control name="WaveRoverSystem" type="system">
        <hardware>
            <xacro:if value="$(arg use_sim)">
                <plugin>gazebo_ros2_control/GazeboSystem</plugin>
            </xacro:if>

            <xacro:unless value="$(arg use_sim)">
                <plugin>waveshare_driver/WaveshareHardware</plugin>
                <param name="device">/dev/ttyUSB0</param>
                <param name="baud_rate">115200</param>
            </xacro:unless>
        </hardware>
        
        <joint name="rear_left_wheel_joint">
            <command_interface name="velocity">
                <param name="min">-10</param>
                <param name="max">10</param>
            </command_interface>
            <state_interface name="velocity"/>
            <state_interface name="position"/>
        </joint>

        <joint name="rear_right_wheel_joint">
            <command_interface name="velocity">
                <param name="min">-10</param>
                <param name="max">10</param>
            </command_interface>
            <state_interface name="velocity"/>
            <state_interface name="position"/>
        </joint>
    </ros2_control>

   <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>$(find rover_control)/config/control.yaml</parameters>
        </plugin>
    </gazebo>

</robot>